feat: husky prettier

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -13,7 +13,7 @@ MSG="[HUSKY][PRE-COMMIT]"
 STAGES=(
   "Start"
   "Formatting with Prettier"
-  "Linting project"
+  # "Linting project"
   "Building project"
   "Testing project"
   "Formatting failed ❌"
@@ -56,12 +56,12 @@ if ! pnpm lint-staged; then
   exit 1
 fi
 
-# Lint
-print_boundary "$YELLOW" "Linting project"
-if ! pnpm lint; then
-  print_boundary "$RED" "Lint failed ❌"
-  exit 1
-fi
+# # Lint
+# print_boundary "$YELLOW" "Linting project"
+# if ! pnpm lint; then
+#   print_boundary "$RED" "Lint failed ❌"
+#   exit 1
+# fi
 
 # Build
 print_boundary "$YELLOW" "Building project"
